const dataMock = [
  {
    id: 1,
    name: "Login page – performance issues",
    text: "",
    status: "Backlog",
    dateMod: 0,
  },
  {
    id: 2,
    name: "Sprint bugfix",
    text: "",
    status: "Backlog",
    dateMod: 0,
  },
  {
    id: 3,
    name: "Shop page – performance issues",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 4,
    name: "Checkout bugfix",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 5,
    name: "Shop bug1",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 6,
    name: "Shop bug2",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 7,
    name: "Shop bug3",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 8,
    name: "Shop bug4",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 9,
    name: "Shop bug5",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 10,
    name: "Shop bug6",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 11,
    name: "Shop page – performance issues",
    text: "",
    status: "Ready",
    dateMod: 0,
  },
  {
    id: 12,
    name: "User page – performance issues",
    text: "",
    status: "In Progress",
    dateMod: 0,
  },
  {
    id: 13,
    name: "Auth bugfix",
    text: "",
    status: "In Progress",
    dateMod: 0,
  },
  {
    id: 14,
    name: "Main page – performance issues",
    text: "",
    status: "Finished",
    dateMod: 0,
  },
  {
    id: 15,
    name: "Main page bugfix",
    text: "",
    status: "Finished",
    dateMod: 0,
  },
];

export default dataMock;
